### ISSUE TITLE
Express throws 404 errors by default, right?

### ISSUE THREAD

**Issue by bramkoot** [Codaisseur/express-recipes-api-demo#1]
https://github.com/Codaisseur/express-recipes-api-demo/blob/3767ce46395313a43daf2140bbf0ac241faa9b66/index.js#L18

**Comment by wearethefoos** [comment]
Not in these types of situations:

https://github.com/Codaisseur/express-recipes-api-demo/blob/3767ce46395313a43daf2140bbf0ac241faa9b66/routes/recipes.js#L16-L18

calling `next()` without arguments now gives you a 404 error
